name: Issue assignment
on:
  issues:
    types: [opened]
jobs:
 auto-assign:
  runs-on: node16
  steps:
  - name: 'Auto-assign issue'
    uses: pozil/auto-assign-issue@v1.0.3
    with:
     repo-token: ${{ secrets.GITHUB_TOKEN }}
     assignees: testesdapri
